### ISSUE TITLE
same error

### ISSUE THREAD

**Issue by xkfen** [novalagung/gubrak#1]
Hello , I'm reading you codes these days,but ,unfortunately i saw some errors in you  return values.
For example,the func Concat,the right return value is :[1 2 3 4 4 6 7 8 9]
                           func TakeRight, the right return value is :[5 6 7 8 9]

**Comment by novalagung** [comment]
Hi, I just checked, it's returning the right value, but the comment is wrong. I just fixed it on #e4d3577
