### ISSUE TITLE
.OrderBy return panic when collection only contains one data

### ISSUE THREAD

**Issue by wnitya2** [novalagung/gubrak#2]
sample code: https://gist.github.com/wnitya2/f0e7ba5c648b7b5b4019da016f5cc425

when collection only contains 1 data, e.g:
```
data := []HashMap{
		{ "name": "tim", "hobby": "stay awake all the time" },
}

result, err := gubrak.OrderBy(data, func(each HashMap) string {
		return each["name"]
})

```

error returns:

> fatal error: all goroutines are asleep - deadlock!
> 
> goroutine 1 [chan send]:
> github.com/novalagung/gubrak.OrderBy.func1.1(0x4df3c0, 0xc042002400, 0x97, 0xc04203c120)
>         D:/Go/src/github.com/novalagung/gubrak/collection.go:888 +0xd9
> github.com/novalagung/gubrak.OrderBy.func1(0x4df3c0, 0xc042002400, 0x4e8780, 0x510aa0, 0x0, 0x0, 0x0, 0xc0420301c0, 0x0, 0x0)
>         D:/Go/src/github.com/novalagung/gubrak/collection.go:1048 +0x4e6
> github.com/novalagung/gubrak.OrderBy(0x4df3c0, 0xc042002400, 0x4e8780, 0x510aa0, 0x0, 0x0, 0x0, 0xc042068060, 0xc04205bf50, 0x4c9db2, ...)
>         D:/Go/src/github.com/novalagung/gubrak/collection.go:1054 +0x9d
> main.main()
>         D:/Go/src/github.com/wnitya2/gubrak-error-orderby/main.go:15 +0x1cd
> exit status 2

**Comment by novalagung** [comment]
I do believe this is due because the `isAsync` property is enabled, and it was the default value. I have changed it to to `false`.

Please do `go get -u`, this issue should be fixed afterwards.
